name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.5.0-31.0.dev <4.0.0'

dependencies:

  dio: ^5.4.3+1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  go_router: ^14.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
