name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.5.0-31.0.dev <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_provider: ^2.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  animate_do: ^2.3.4
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
